server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: zone-service
          uri: lb://ZONE-SERVICE
          predicates:
            - Path=/api/zones/**
          filters:
            - name: Authentication

        - id: sensor-service
          uri: lb://SENSOR-SERVICE
          predicates:
            - Path=/api/sensors/**
          filters:
            - name: Authentication

        - id: crop-service
          uri: lb://CROP-INVENTORY-SERVICE
          predicates:
            - Path=/api/crops/**
          filters:
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: s1yrp6ObnCom75pEyGg4gKJrdV8ViStJVI532bUreW1

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG